// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcIIPifH5HPJjWtEg1e7XoavY8ATCxV0',
    appId: '1:688090303624:android:b96c59cb4ed16e8d25a33d',
    messagingSenderId: '688090303624',
    projectId: 'estehnusantara-ea938',
    databaseURL: 'https://estehnusantara-ea938-default-rtdb.firebaseio.com',
    storageBucket: 'estehnusantara-ea938.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPl__Aya2Cm2RulKBCTLJ1YbWffrRewPI',
    appId: '1:688090303624:web:f0cf440d54968dac25a33d',
    messagingSenderId: '688090303624',
    projectId: 'estehnusantara-ea938',
    authDomain: 'estehnusantara-ea938.firebaseapp.com',
    databaseURL: 'https://estehnusantara-ea938-default-rtdb.firebaseio.com',
    storageBucket: 'estehnusantara-ea938.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA4G_q6SiiX17h-bRRtTcQEkER1l82pOI',
    appId: '1:688090303624:ios:11521099cbcf085d25a33d',
    messagingSenderId: '688090303624',
    projectId: 'estehnusantara-ea938',
    databaseURL: 'https://estehnusantara-ea938-default-rtdb.firebaseio.com',
    storageBucket: 'estehnusantara-ea938.appspot.com',
    iosBundleId: 'com.example.lji',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA4G_q6SiiX17h-bRRtTcQEkER1l82pOI',
    appId: '1:688090303624:ios:11521099cbcf085d25a33d',
    messagingSenderId: '688090303624',
    projectId: 'estehnusantara-ea938',
    databaseURL: 'https://estehnusantara-ea938-default-rtdb.firebaseio.com',
    storageBucket: 'estehnusantara-ea938.appspot.com',
    iosBundleId: 'com.example.lji',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPl__Aya2Cm2RulKBCTLJ1YbWffrRewPI',
    appId: '1:688090303624:web:8b4e95628997398825a33d',
    messagingSenderId: '688090303624',
    projectId: 'estehnusantara-ea938',
    authDomain: 'estehnusantara-ea938.firebaseapp.com',
    databaseURL: 'https://estehnusantara-ea938-default-rtdb.firebaseio.com',
    storageBucket: 'estehnusantara-ea938.appspot.com',
  );

}